### ISSUE TITLE
How to set the installation parameters for oatpp?

### ISSUE THREAD

**Issue by surfingtomchen** [oatpp/oatpp-websocket#15]
Sorry I am not familiar with cmake. I try to do following steps in windows

```
mkdir build
cd bulid
cmake ..
```

but I get following error:

```
Finding oatpp in location=INSTALLED
CMake Error at CMakeLists.txt:41 (find_package):
  By not providing "Findoatpp.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "oatpp", but
  CMake did not find one.
```

do I need to revise the cmake file to setup the previous installation dir of oatpp?

**Comment by lganzzzo** [comment]
Hey @surfingtomchen ,

You need to install the `oatpp` first. In order for `oatpp-websocket` to find it.

oatpp:

```bash
$ mkdir build
$ cd build/
$ cmake ..
$ make install     # - build and install oatpp
```

Same for every oatpp module that you are planning to use.

Please let me know if you have more questions.

Regards,
Leonid

**Comment by lganzzzo** [comment]
So in order to build a web app which uses `oatpp` and `oatpp-websocket` you have to do:

1. build and install `oatpp`

   ```bash
   $ mkdir build
   $ cd build/
   $ cmake ..
   $ make install     # - build and install oatpp
   ```
2. build and install `oatpp-websocket`

   ```bash
   $ mkdir build
   $ cd build/
   $ cmake ..
   $ make install     # - build and install oatpp-websocket
   ```

3. build your application

   ```bash
   $ mkdir build
   $ cd build/
   $ cmake ..
   $ make      # - generate executable
   ```

---

On windows:

```bash
$ MD build                            # - create build folder
$ cd build\                           # - go to build folder
$ cmake ..                            # - generate VS project
$ cmake --build . --target INSTALL    # - install oatpp module
```

---

Regards,
Leonid

**Comment by surfingtomchen** [comment]
@lganzzzo really helps. thank you very much.
