### ISSUE TITLE
chrome receives wrong reserved bits

### ISSUE THREAD

**Issue by longlonghands** [oatpp/oatpp-websocket#17]
Sometimes when I trying to connect to WebSocket server using Chrome I get this error:
One or more reserved bits are on: reserved1 = 1, reserved2 = 1, reserved3 = 1

can you help me figure out what is going wrong? 
Chrome is the latest version (79). and the oat-websocket version is 0.19.9. and I'm sending big messages (from 1K to 1MB) using simple non-async WebSocket.

**Comment by lganzzzo** [comment]
Hello @longlonghands ,

Please try to update oatpp to the `0.19.12` version. A lot of bugs were fixed since `0.19.9`.

Please let me know if the issue still there after the update.

Best Regards,
Leonid

**Comment by longlonghands** [comment]
Hello Leonid,
Thank you for your prompt response. I hope your suggestion will resolve the issue. I'm gonna update the library and will test it. 
I will inform you of the results for sure. but it will take some time.

Best,
Shahin

**Comment by lganzzzo** [comment]
No worries, I'll wait for results.

Regards,
Leonid

**Comment by longlonghands** [comment]
Hi Leonid,
After updating to `0.9.12` and running the code in multiple environments, I think the issue has been resolved. So I'm gonna close this issue.
Thanks again for your great work. `oatpp` seems an incredible library to be used in C++ projects.

Regards,
Shahin

**Comment by lganzzzo** [comment]
Hey @longlonghands ,
Thanks for the test, and for posting the result!
