### ISSUE TITLE
example for multiframe/ChunkedBuffer usage

### ISSUE THREAD

**Issue by r2dliu** [oatpp/oatpp-websocket#18]
Hello,

I am trying to send a message through a websocket from my server to a client. I want to send a rather large message, a struct that contains something on the order of several megabytes worth of data.

I see a few methods and the example implementation for sending one frame of text/small strings, but am not sure of the correct way to do multiframe or large pieces of fixed size byte data.

Could you provide an example or point me in the right direction?

**Comment by bhorn** [comment]
Hello there,

what are you trying to archive? In general, WS are a stream an a single WS-Frame can grow up to 2^63 bytes (9,223,372,036,854,775,807 bytes ~ 9.22 exabytes). So its only a matter of how you are managing your data. So if you want to chunk your data, just send them in chunks of your liking.

Can you elaborate more on your use-case so we can come up with an nice idea?

**Comment by lganzzzo** [comment]
Hello,

Also, you can manually send a multi-frame message:

```cpp

ws->sendOneFrame(false /*fin*/, Frame::OPCODE_TEXT         /*opcode*/, "Hello"  /*first message part*/);
ws->sendOneFrame(false /*fin*/, Frame::OPCODE_CONTINUATION /*opcode*/, " "      /*continuation message part*/);
ws->sendOneFrame(true  /*fin*/, Frame::OPCODE_CONTINUATION /*opcode*/, "World!" /*last message part*/);

```

And in the future, we plan to introduce a convenience API for this.

Regards,
Leonid

**Comment by r2dliu** [comment]
currently I'm trying something similar to this:
`my_struct const &curr_struct; //very large struct with lots of data ` 
`auto bytes= reinterpret_cast<char*>(&const_cast<my_struct>&>(curr_struct));`
`oatpp::String string(bytes, sizeof(my_struct)), false);`
`socket->sendOneFrameBinary(string);`

other end parses 
`auto wholeMessage = m_messageBuffer.toString();`
`my_struct * test = (my_struct*)reinterpret_cast<char*>(&wholeMessage);`
and then receiving it on the other end, but it doesn't seem to parse properly.

**Comment by r2dliu** [comment]
nvm, I have gotten it to work, just misunderstood how oatpp::String worked under the hood.

Worked once I started using getData() to retrieve directly the pointer to the bytes received when sending a binary frame.

**Comment by lganzzzo** [comment]
Hey @r2dliu ,

Please also take into account that the approach mentioned in the previous comment (with reinterpreting bytes to/from struct/string) is working for sending/receiving messages between machines with the same byte-order only. And will fail for communication between machines with different byte-order.

In order to have consistent and portable serialization/deserialization on machines with different byte-orders, you may use oatpp DTOs with custom ObjectMapper.

Regards,
Leonid
