### ISSUE TITLE
Multiple calls to onBeforeDestroy

### ISSUE THREAD

**Issue by c-lgrant** [oatpp/oatpp-websocket#3]
Hey, 

I have noticed that for the websocket connections. i see that onBeforeDestroy is called twice is this expected?
```
        void onBeforeDestroy(const oatpp::websocket::WebSocket& socket) override {
            OATPP_LOGD(TAG, "Closing connection");
        }
```
produces 
```
MySocketInstanceListener Closing connection
MySocketInstanceListener Closing connection
```

Is this expected

Thanks 

Conor

**Comment by lganzzzo** [comment]
Hey @c-lgrant 

Please see fix for this issue!

Best Regards,
Leonid

**Comment by c-lgrant** [comment]
Hey, 

Perfect that works as expected.

Thank you for your quick response !

Regards

**Comment by c-lgrant** [comment]
@lganzzzo 

Is there a way to get the remote ip address of the socket?

i want to try to log every new socket connection

Thanks

Conor

**Comment by lganzzzo** [comment]
@c-lgrant 

>Is there a way to get the remote ip address of the socket? i want to try to log every new socket connection

Currently it is not possible.

I plan to add possibility to bind bundle of optional properties to `output::data::IOStream` sometime in future.

I think I'll get to it in something like a month from now.

Regards,
Leonid
